### ISSUE TITLE
Records

### ISSUE THREAD

**Issue by akovari** [yatta-lang/yatta#15]
- Implemented using tuples, where the first element is the name of the record
- Syntax sugar, derived from tuple syntax, that is removed during parsing
- Records are module scoped

- [x] Declaration syntax:

`record Person = (first_name, last_name)`

- [x] New record syntax:

`let person = Person(first_name = "Adam")  # at least one field is required, although it can technically be ()`

- [x] Field access syntax:

`person.first_name`

- [x] Pattern matching syntax:

`fun Person(first_name=f, last_name=l)  # where f and l are bound to the values of first/last name from that record`

`fun p@Person  # way to access the whole record in pattern matching, similar to sequences for example`

- [x] Update record field:

`let new_record = old_record(field = value)`

**Comment by akovari** [comment]
@kurobako I updated this with what I'm thinking could be done pretty quickly...

**Comment by kurobako** [comment]
I am not sure if I like (foo, bar) syntax since it looks like a tuple (yes it is, but element indices are different since first one is the symbol. Can we use something else instead? { } are free iirc, wdyt?
