### ISSUE TITLE
Generators

### ISSUE THREAD

**Issue by akovari** [yatta-lang/yatta#16]
- [x] **Seq** comprehension:
`[a * 2 | a <- [1, 2]]`
- [x] **Seq** comprehension with a filter:
`[a * 2 | a <- [1, 2] if a > 2]`

- [x] **Dict** comprehension:
`{a = 2 | a <- [1, 2]}`
- [x] **Dict** comprehension with a filter:
`{key = val * 2 | key = val <- {1: 2, 3: 4} if val > 2}`

- [x] **Set** comprehension:
`{a * 2 | a <- [1, 2]}`
- [x] **Set** comprehension with a filter:
`{a * 2 | a <- [1, 2] if a + b > 3}`

**Comment by kurobako** [comment]
Please take a look when you have a moment and when we meet I can comment on that if needed:

https://github.com/kurobako/agave/blob/master/src/main/java/io/github/kurobako/agave/Reducer.java
https://github.com/kurobako/agave/blob/master/src/main/java/io/github/kurobako/agave/Transducers.java

My suggestion is we implement this in our language in standard library (I think it will be short and pretty) and make generators sugar for it.

**Comment by akovari** [comment]
**Seq** comprehension:
`[a * b | a <- [1, 2], b <- [1, 2, 3]]`
**Seq** comprehension with a filter:
`[a * b | a <- [1, 2], b <- [1, 2, 3] if a + b > 3]`

**Dict** comprehension:
`{a: b | a <- [1, 2], b <- [1, 2, 3]}`
**Dict** comprehension with a filter:
`{a: b | a: b <- {1: 2, 3: 4} if a + b > 3}`

**Set** comprehension:
`{a * b | a <- [1, 2], b <- [1, 2, 3]}`
**Set** comprehension with a filter:
`{a * b | a <- [1, 2], b <- [1, 2, 3] if a + b > 3}`

**Arbitrary collection** comprehension using transducer:
`(take 2 | a ++ b | a <- ["ab", "cd"], b <- ["ef", "gh"] if String.length (a + b) > 2)`
in this case, `a ++ b` evaluates into sequence (string), so `take 2` transducer is passed to `Seq.transduce` with `a ++ b` as the sequence to transform itself.

@kurobako wdyt?
