### ISSUE TITLE
Strings

### ISSUE THREAD

**Issue by akovari** [yatta-lang/yatta#2]
Strings are on the surface represented as lists of characters. Character is a UTF-8 character.

Character represented using java int type.

Other features
------------------
- [x] character represented as java int. In the language, it has a dedicated type: `'a'`
- [x] multi-line
```
  "
  The quick brown fox
  jumps over the lazy dog
  "
```
- [x] interpolation
```"Hello {name}."```

- [x] pattern matching

**Comment by kurobako** [comment]
Not all operations on strings in their byte arrayruntime  representation will convert them to actual lists (tree-like structure akin to haskell Sequence in our case). folds, maps and such work perfectly fine on arrays. However, when operation such as : or ++ is called, we do conversion.
 
This all requires runtime profiling though, more than it might be seen at first: sometimes it's better to convert source string, sometimes we only care about resulting string being represented as list.
