### ISSUE TITLE
[interop] getMembers should not return a String[]

### ISSUE THREAD

**Issue by fniephaus** [yatta-lang/yatta#54]
Problem is in [YattaModule.java](https://github.com/yatta-lang/yatta/blob/a572e099f2a12a1e7065edc6a17ea5cc9bbe554a/language/src/main/java/yatta/runtime/YattaModule.java#L105). See [SimpleLanguage example](https://github.com/graalvm/simplelanguage/blob/41a21a604451298fb8eb82e8cb0d5e7299723262/language/src/main/java/com/oracle/truffle/sl/runtime/FunctionsObject.java#L83).

The error indicates that the interop contract was violated:
<img width="861" alt="image" src="https://user-images.githubusercontent.com/2368856/83042793-586c4e00-a042-11ea-96f6-8a5bba16fb81.png">

**Comment by akovari** [comment]
Thanks, I can look into this a bit later in the week, unless you want to give it a try before I do.
